/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author informatica
 */
public class abaVenda extends javax.swing.JPanel {

    /**
     * Creates new form abaVenda
     */
    public abaVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selFilme = new javax.swing.JComboBox<>();
        lbFilme = new javax.swing.JLabel();
        lbSessao = new javax.swing.JLabel();
        selSessao = new javax.swing.JComboBox<>();
        lbCpfCliente = new javax.swing.JLabel();
        codCPFCliVenda = new javax.swing.JTextField();
        btSlFilmeCancelar = new javax.swing.JButton();
        btOkVenda = new javax.swing.JButton();
        texto = new javax.swing.JLabel();
        selQuantIngresso = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(720, 430));

        selFilme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selFilme.setToolTipText("Seleção do filme, que o cliente deseja.");
        selFilme.setNextFocusableComponent(selSessao);
        selFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selFilmeActionPerformed(evt);
            }
        });

        lbFilme.setText("Filme:");

        lbSessao.setText("Sessão");

        selSessao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selSessao.setToolTipText("Seleção da sessão que o cliente deseja.");
        selSessao.setNextFocusableComponent(selQuantIngresso);

        lbCpfCliente.setText("CPF do Cliente (opcional):");

        codCPFCliVenda.setToolTipText("Cpf do cliente cadastrado.");
        codCPFCliVenda.setNextFocusableComponent(btOkVenda);

        btSlFilmeCancelar.setText("Cancelar");
        btSlFilmeCancelar.setNextFocusableComponent(selFilme);

        btOkVenda.setText("Confirmar");
        btOkVenda.setNextFocusableComponent(btSlFilmeCancelar);

        texto.setText("Quantidade de ingressos:");

        selQuantIngresso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selQuantIngresso.setNextFocusableComponent(codCPFCliVenda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btOkVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btSlFilmeCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codCPFCliVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbCpfCliente)
                        .addComponent(lbSessao)
                        .addComponent(lbFilme)
                        .addComponent(selSessao, 0, 374, Short.MAX_VALUE)
                        .addComponent(selFilme, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(selQuantIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btOkVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbFilme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbSessao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(texto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selQuantIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbCpfCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(codCPFCliVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(btSlFilmeCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selFilmeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOkVenda;
    private javax.swing.JButton btSlFilmeCancelar;
    private javax.swing.JTextField codCPFCliVenda;
    private javax.swing.JLabel lbCpfCliente;
    private javax.swing.JLabel lbFilme;
    private javax.swing.JLabel lbSessao;
    private javax.swing.JComboBox<String> selFilme;
    private javax.swing.JComboBox<String> selQuantIngresso;
    private javax.swing.JComboBox<String> selSessao;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
