package GUI;

import Objetos.Extended.ObjectComboModel;
import Objetos.Extended.FilmeTableModel;
import java.awt.Toolkit;
import java.util.ArrayList;
import Objetos.Filme;
import Objetos.FilmeDAO;
import Objetos.Extended.JNumberTextField;
import Objetos.Sala;
import Objetos.SalaDAO;
import Objetos.Sessao;
import Objetos.Vendedor;
import Objetos.VendedorDAO;
import Tools.Msgs;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

public class PainelGerente extends javax.swing.JFrame {

    private FilmeTableModel ftm;
    private static ArrayList<Filme> listaFilmes;
    private static ArrayList<Vendedor> listaVendedores;
    private static ArrayList<Sala> listaSalas;
    private HashMap<String, Integer> vends;
    private HashMap<String, Integer> films;

    static void start() {
        java.awt.EventQueue.invokeLater(() -> {
            new PainelGerente().setVisible(true);
        });
    }

    public PainelGerente() {
        initComponents();
        try {
            loadDAOs();
            ftm = new FilmeTableModel();
            rmvFilmeTable.setModel(ftm);
            newSessaoFilme.setModel(new ObjectComboModel(listaFilmes.toArray(), "Filme"));
            newSessaoSala.setModel(new ObjectComboModel(listaSalas.toArray(), "Sala"));

        } catch (SQLException ex) {
            System.out.println("Erro do SQL!");
            Logger.getLogger(PainelGerente.class.getName()).log(Level.SEVERE, null, ex);
        }
        //alocaFilmesNaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabsGerente = new javax.swing.JTabbedPane();
        gerentePanelAdd = new javax.swing.JPanel();
        adicionarTabs = new javax.swing.JTabbedPane();
        panelAddFilme = new javax.swing.JPanel();
        newFilmeNome = new javax.swing.JTextField();
        newFilmeNomeLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        newFilmeSinopse = new javax.swing.JTextArea();
        newFilmeSinposeLabel = new javax.swing.JLabel();
        newFilmeGenLabel = new javax.swing.JLabel();
        newFilmeBtnSave = new javax.swing.JButton();
        newFilmeAnoLabel = new javax.swing.JLabel();
        newFilmeAno = new javax.swing.JSlider(1900, 2017,2000);
        newFilmeAnoCurrentLabel = new javax.swing.JLabel();
        newFilmeAnoCurrent = new javax.swing.JLabel();
        newFilmeBtnClear = new javax.swing.JButton();
        newFilmeGeneros = new javax.swing.JTextField();
        painelAddSala = new javax.swing.JPanel();
        newSalaNomeLabel = new javax.swing.JLabel();
        newSalaNome = new javax.swing.JTextField();
        newSalaCodLabel = new javax.swing.JLabel();
        newSalaCod = new JNumberTextField();
        newSalaBtnSave = new javax.swing.JButton();
        newSalaBtnClear = new javax.swing.JButton();
        painelAddSessao = new javax.swing.JPanel();
        newSessaoFilmeLabel = new javax.swing.JLabel();
        newSessaoPrecoLabel = new javax.swing.JLabel();
        newSessaoFilme = new JComboBox<Object>();
        newSessaoTime = new javax.swing.JLabel();
        newSessaoSala = new JComboBox<Object>();
        newSessaoSalaLabel = new javax.swing.JLabel();
        newSessaoBtnSave = new javax.swing.JButton();
        newSessaoBtnClear = new javax.swing.JButton();
        newSessaoHoras = new JNumberTextField(3);
        newSessaoMinutos = new JNumberTextField(3);
        newSessaoTime1 = new javax.swing.JLabel();
        newSessaoPreco = new JNumberTextField(3);
        painelAddVendedor = new javax.swing.JPanel();
        newVendedorCPFLabel = new javax.swing.JLabel();
        newVendedorCPF = new JNumberTextField(11);
        newVendedorTurnoLabel = new javax.swing.JLabel();
        newVendedorTurno = new javax.swing.JComboBox<>();
        newVendedorEmailLabel = new javax.swing.JLabel();
        newVendedorEmail = new javax.swing.JTextField();
        newVendedorBtnSave = new javax.swing.JButton();
        newVendedorLoginLabel = new javax.swing.JLabel();
        newVendedorLogin = new javax.swing.JTextField();
        newVendedorSenhaLabel = new javax.swing.JLabel();
        newVendedorSenha = new javax.swing.JPasswordField();
        newVendedorBtnClear = new javax.swing.JButton();
        gerentePanelRem = new javax.swing.JPanel();
        removerTabs = new javax.swing.JTabbedPane();
        painelRmvFilme = new javax.swing.JPanel();
        rmvFilmeOptLabel = new javax.swing.JLabel();
        rmvFilmeBtnYes = new javax.swing.JButton();
        rmvFilmeTableOutside = new javax.swing.JScrollPane();
        rmvFilmeTable = new javax.swing.JTable();
        painelRmvSala = new javax.swing.JPanel();
        rmvSalaOpt = new JNumberTextField();
        rmvSalaOptLabel = new javax.swing.JLabel();
        rmvSalaBtnYes = new javax.swing.JButton();
        painelRmvSessao = new javax.swing.JPanel();
        rmvSessaoOptLabel = new javax.swing.JLabel();
        rmvSessaoOpt = new javax.swing.JComboBox<>();
        rmvSessaoBtnClear = new javax.swing.JButton();
        rmvSessaoBtnYes = new javax.swing.JButton();
        painelRmvVendedor = new javax.swing.JPanel();
        rmvVendedorCPFLabel = new javax.swing.JLabel();
        rmvVendedorCPF = new JNumberTextField(11);
        rmvVendBtnClear = new javax.swing.JButton();
        rmvVendPrevEmail = new javax.swing.JTextField();
        rmvVendPrevEmailLabel = new javax.swing.JLabel();
        rmvVendPrevLogin = new javax.swing.JTextField();
        rmvVendPrevLoginLabel = new javax.swing.JLabel();
        rmvVendPrevTurnoLabel = new javax.swing.JLabel();
        rmvVendPrevTurno = new javax.swing.JTextField();
        tituloPainelGerente = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());

        tabsGerente.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tabsGerente.setToolTipText("Painel utilizado pelo gerente para adicionar um novo filme/sessão/sala/funcionário");

        newFilmeNome.setToolTipText("Digite o nome do filme ser disponibilizado. Deve ser diferente dos já cadastrados.");
        newFilmeNome.setNextFocusableComponent(newFilmeSinopse);
        newFilmeNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFilmeNomeActionPerformed(evt);
            }
        });

        newFilmeNomeLabel.setText("Título do Filme:");

        newFilmeSinopse.setColumns(20);
        newFilmeSinopse.setRows(5);
        newFilmeSinopse.setToolTipText("Digite uma sinopse para o filme.");
        jScrollPane1.setViewportView(newFilmeSinopse);
        newFilmeSinopse.getAccessibleContext().setAccessibleName("");

        newFilmeSinposeLabel.setText("Sinopse:");

        newFilmeGenLabel.setText("Gêneros:");

        newFilmeBtnSave.setText("Salvar Filme");
        newFilmeBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFilmeBtnSaveActionPerformed(evt);
            }
        });

        newFilmeAnoLabel.setText("Ano do Filme");

        newFilmeAno.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                newFilmeAnoStateChanged(evt);
            }
        });

        newFilmeAnoCurrentLabel.setText("Valor atual:");

        newFilmeAnoCurrent.setText("2000");

        newFilmeBtnClear.setText("Limpar Campos");
        newFilmeBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFilmeBtnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAddFilmeLayout = new javax.swing.GroupLayout(panelAddFilme);
        panelAddFilme.setLayout(panelAddFilmeLayout);
        panelAddFilmeLayout.setHorizontalGroup(
            panelAddFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddFilmeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newFilmeGeneros, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addGroup(panelAddFilmeLayout.createSequentialGroup()
                        .addGroup(panelAddFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newFilmeNome, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newFilmeNomeLabel)
                            .addComponent(newFilmeSinposeLabel)
                            .addComponent(newFilmeGenLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelAddFilmeLayout.createSequentialGroup()
                        .addComponent(newFilmeAnoLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(newFilmeAno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelAddFilmeLayout.createSequentialGroup()
                        .addGap(0, 194, Short.MAX_VALUE)
                        .addComponent(newFilmeBtnSave)
                        .addGap(80, 80, 80)
                        .addComponent(newFilmeBtnClear)
                        .addGap(0, 195, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddFilmeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(newFilmeAnoCurrentLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newFilmeAnoCurrent)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAddFilmeLayout.setVerticalGroup(
            panelAddFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddFilmeLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(newFilmeNomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newFilmeNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newFilmeSinposeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newFilmeGenLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newFilmeGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(newFilmeAnoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newFilmeAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newFilmeAnoCurrentLabel)
                    .addComponent(newFilmeAnoCurrent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newFilmeBtnSave)
                    .addComponent(newFilmeBtnClear))
                .addContainerGap())
        );

        adicionarTabs.addTab("Filme", panelAddFilme);

        newSalaNomeLabel.setText("Nome da Sala:");

        newSalaNome.setToolTipText("Digite o nome da nova sala a ser cadastrada.");
        newSalaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSalaNomeActionPerformed(evt);
            }
        });

        newSalaCodLabel.setText("Código da Sala:");

        newSalaCod.setToolTipText("Digite o código da nova sala a ser cadastrada.");

        newSalaBtnSave.setText("Salvar");
        newSalaBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSalaBtnSaveActionPerformed(evt);
            }
        });

        newSalaBtnClear.setText("Limpar Campos");
        newSalaBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSalaBtnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelAddSalaLayout = new javax.swing.GroupLayout(painelAddSala);
        painelAddSala.setLayout(painelAddSalaLayout);
        painelAddSalaLayout.setHorizontalGroup(
            painelAddSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAddSalaLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addGroup(painelAddSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newSalaCodLabel)
                    .addComponent(newSalaNomeLabel)
                    .addGroup(painelAddSalaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(painelAddSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelAddSalaLayout.createSequentialGroup()
                                .addComponent(newSalaBtnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(newSalaBtnClear))
                            .addComponent(newSalaNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newSalaCod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        painelAddSalaLayout.setVerticalGroup(
            painelAddSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAddSalaLayout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addComponent(newSalaNomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newSalaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newSalaCodLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newSalaCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelAddSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newSalaBtnSave)
                    .addComponent(newSalaBtnClear))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        adicionarTabs.addTab("Sala", painelAddSala);

        newSessaoFilmeLabel.setText("Filme:");

        newSessaoPrecoLabel.setText("Preço:");

        newSessaoFilme.setToolTipText("Selecione o filme ");

        newSessaoTime.setText("Horário de início(HH:MM):");

        newSessaoSala.setToolTipText("Selecione a Sala");
        newSessaoSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSessaoSalaActionPerformed(evt);
            }
        });

        newSessaoSalaLabel.setText("Sala:");

        newSessaoBtnSave.setText("Salvar");
        newSessaoBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSessaoBtnSaveActionPerformed(evt);
            }
        });

        newSessaoBtnClear.setText("Limpar Campos");
        newSessaoBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSessaoBtnClearActionPerformed(evt);
            }
        });

        newSessaoHoras.setToolTipText("Digite as horas.");
        newSessaoHoras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                newSessaoHorasFocusLost(evt);
            }
        });
        newSessaoHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSessaoHorasActionPerformed(evt);
            }
        });
        newSessaoHoras.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                newSessaoHorasPropertyChange(evt);
            }
        });
        newSessaoHoras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newSessaoHorasKeyTyped(evt);
            }
        });

        newSessaoMinutos.setToolTipText("Digite os minutos.");
        newSessaoMinutos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                newSessaoMinutosFocusLost(evt);
            }
        });
        newSessaoMinutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSessaoMinutosActionPerformed(evt);
            }
        });
        newSessaoMinutos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                newSessaoMinutosPropertyChange(evt);
            }
        });
        newSessaoMinutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newSessaoMinutosKeyTyped(evt);
            }
        });

        newSessaoTime1.setText(":");

        newSessaoPreco.setToolTipText("Digite as horas.");
        newSessaoPreco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                newSessaoPrecoFocusLost(evt);
            }
        });
        newSessaoPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSessaoPrecoActionPerformed(evt);
            }
        });
        newSessaoPreco.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                newSessaoPrecoPropertyChange(evt);
            }
        });
        newSessaoPreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newSessaoPrecoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout painelAddSessaoLayout = new javax.swing.GroupLayout(painelAddSessao);
        painelAddSessao.setLayout(painelAddSessaoLayout);
        painelAddSessaoLayout.setHorizontalGroup(
            painelAddSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAddSessaoLayout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(painelAddSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAddSessaoLayout.createSequentialGroup()
                        .addComponent(newSessaoTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newSessaoHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newSessaoTime1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newSessaoMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelAddSessaoLayout.createSequentialGroup()
                        .addGroup(painelAddSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newSessaoFilmeLabel)
                            .addComponent(newSessaoSalaLabel))
                        .addGap(18, 18, 18)
                        .addGroup(painelAddSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newSessaoFilme, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newSessaoSala, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelAddSessaoLayout.createSequentialGroup()
                        .addComponent(newSessaoPrecoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelAddSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelAddSessaoLayout.createSequentialGroup()
                                .addComponent(newSessaoBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(newSessaoBtnClear))
                            .addComponent(newSessaoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        painelAddSessaoLayout.setVerticalGroup(
            painelAddSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAddSessaoLayout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(painelAddSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newSessaoFilmeLabel)
                    .addComponent(newSessaoFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelAddSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newSessaoSalaLabel)
                    .addComponent(newSessaoSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelAddSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newSessaoTime)
                    .addComponent(newSessaoHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newSessaoMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newSessaoTime1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelAddSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newSessaoPrecoLabel)
                    .addComponent(newSessaoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(painelAddSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newSessaoBtnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newSessaoBtnClear))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        adicionarTabs.addTab("Sessão", painelAddSessao);

        newVendedorCPFLabel.setText("CPF:");

        newVendedorCPF.setToolTipText("Digite o CPF do funcionário a aser cadastrado.");

        newVendedorTurnoLabel.setText("Turno:");

        newVendedorTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Matutino", "Vespertinho", "Noturno"}));
        newVendedorTurno.setToolTipText("Selecione o turno do funcionário.");

        newVendedorEmailLabel.setText("Email");

        newVendedorEmail.setToolTipText("Digite o e-mail do funcionário a ser cadatrado.");

        newVendedorBtnSave.setText("Salvar");
        newVendedorBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newVendedorBtnSaveActionPerformed(evt);
            }
        });

        newVendedorLoginLabel.setText("Login");

        newVendedorSenhaLabel.setText("Senha");

        newVendedorBtnClear.setText("Limpar Campos");
        newVendedorBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newVendedorBtnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelAddVendedorLayout = new javax.swing.GroupLayout(painelAddVendedor);
        painelAddVendedor.setLayout(painelAddVendedorLayout);
        painelAddVendedorLayout.setHorizontalGroup(
            painelAddVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAddVendedorLayout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addGroup(painelAddVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newVendedorSenhaLabel)
                    .addComponent(newVendedorLoginLabel)
                    .addComponent(newVendedorCPFLabel)
                    .addComponent(newVendedorCPF)
                    .addComponent(newVendedorTurnoLabel)
                    .addComponent(newVendedorTurno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newVendedorEmailLabel)
                    .addComponent(newVendedorEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addGroup(painelAddVendedorLayout.createSequentialGroup()
                        .addComponent(newVendedorBtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newVendedorBtnClear))
                    .addComponent(newVendedorLogin)
                    .addComponent(newVendedorSenha))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        painelAddVendedorLayout.setVerticalGroup(
            painelAddVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAddVendedorLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(newVendedorCPFLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newVendedorCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newVendedorTurnoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newVendedorTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newVendedorEmailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newVendedorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newVendedorLoginLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newVendedorLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newVendedorSenhaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newVendedorSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelAddVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newVendedorBtnSave)
                    .addComponent(newVendedorBtnClear))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        adicionarTabs.addTab("Vendedor", painelAddVendedor);

        javax.swing.GroupLayout gerentePanelAddLayout = new javax.swing.GroupLayout(gerentePanelAdd);
        gerentePanelAdd.setLayout(gerentePanelAddLayout);
        gerentePanelAddLayout.setHorizontalGroup(
            gerentePanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adicionarTabs, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        gerentePanelAddLayout.setVerticalGroup(
            gerentePanelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adicionarTabs, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        tabsGerente.addTab("Adicionar", gerentePanelAdd);

        rmvFilmeOptLabel.setText("Escolha o Filme:");

        rmvFilmeBtnYes.setText("Remover filme selecionado");
        rmvFilmeBtnYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmvFilmeBtnYesActionPerformed(evt);
            }
        });

        rmvFilmeTable.setNextFocusableComponent(rmvFilmeBtnYes);
        rmvFilmeTableOutside.setViewportView(rmvFilmeTable);

        javax.swing.GroupLayout painelRmvFilmeLayout = new javax.swing.GroupLayout(painelRmvFilme);
        painelRmvFilme.setLayout(painelRmvFilmeLayout);
        painelRmvFilmeLayout.setHorizontalGroup(
            painelRmvFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRmvFilmeLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(painelRmvFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rmvFilmeTableOutside, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                    .addComponent(rmvFilmeOptLabel))
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelRmvFilmeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rmvFilmeBtnYes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelRmvFilmeLayout.setVerticalGroup(
            painelRmvFilmeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRmvFilmeLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(rmvFilmeOptLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rmvFilmeTableOutside, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rmvFilmeBtnYes)
                .addGap(33, 33, 33))
        );

        removerTabs.addTab("Filme", painelRmvFilme);

        rmvSalaOpt.setToolTipText("Digite o código da sala a ser removida.");

        rmvSalaOptLabel.setText("Código da Sala:");

        rmvSalaBtnYes.setText("Confirmar");
        rmvSalaBtnYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmvSalaBtnYesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelRmvSalaLayout = new javax.swing.GroupLayout(painelRmvSala);
        painelRmvSala.setLayout(painelRmvSalaLayout);
        painelRmvSalaLayout.setHorizontalGroup(
            painelRmvSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRmvSalaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelRmvSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rmvSalaOpt, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rmvSalaOptLabel)
                    .addComponent(rmvSalaBtnYes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelRmvSalaLayout.setVerticalGroup(
            painelRmvSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRmvSalaLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(rmvSalaOptLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rmvSalaOpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rmvSalaBtnYes)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        removerTabs.addTab("Sala", painelRmvSala);

        rmvSessaoOptLabel.setText("Sala:");

        rmvSessaoOpt.setToolTipText("Selecione a sala a ser removida.");

        rmvSessaoBtnClear.setText("Reiniciar seleção");
        rmvSessaoBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmvSessaoBtnClearActionPerformed(evt);
            }
        });

        rmvSessaoBtnYes.setText("Confirmar");

        javax.swing.GroupLayout painelRmvSessaoLayout = new javax.swing.GroupLayout(painelRmvSessao);
        painelRmvSessao.setLayout(painelRmvSessaoLayout);
        painelRmvSessaoLayout.setHorizontalGroup(
            painelRmvSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRmvSessaoLayout.createSequentialGroup()
                .addContainerGap(223, Short.MAX_VALUE)
                .addGroup(painelRmvSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelRmvSessaoLayout.createSequentialGroup()
                        .addComponent(rmvSessaoBtnYes, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rmvSessaoBtnClear))
                    .addComponent(rmvSessaoOptLabel)
                    .addComponent(rmvSessaoOpt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        painelRmvSessaoLayout.setVerticalGroup(
            painelRmvSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRmvSessaoLayout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(rmvSessaoOptLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rmvSessaoOpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(painelRmvSessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rmvSessaoBtnYes)
                    .addComponent(rmvSessaoBtnClear))
                .addContainerGap(237, Short.MAX_VALUE))
        );

        removerTabs.addTab("Sessão", painelRmvSessao);

        rmvVendedorCPFLabel.setText("CPF:");

        rmvVendedorCPF.setToolTipText("Digite o CPF do funcionário a ser removido.");
        rmvVendedorCPF.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                rmvVendedorCPFCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        rmvVendedorCPF.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                rmvVendedorCPFPropertyChange(evt);
            }
        });
        rmvVendedorCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rmvVendedorCPFKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rmvVendedorCPFKeyReleased(evt);
            }
        });

        rmvVendBtnClear.setText("Cancelar");

        rmvVendPrevEmail.setEnabled(false);
        rmvVendPrevEmail.setFocusable(false);

        rmvVendPrevEmailLabel.setText("Email Vendedor");

        rmvVendPrevLogin.setEnabled(false);
        rmvVendPrevLogin.setFocusable(false);

        rmvVendPrevLoginLabel.setText("Login Vendedor");

        rmvVendPrevTurnoLabel.setText("Turno Vendedor");

        rmvVendPrevTurno.setEnabled(false);
        rmvVendPrevTurno.setFocusable(false);

        javax.swing.GroupLayout painelRmvVendedorLayout = new javax.swing.GroupLayout(painelRmvVendedor);
        painelRmvVendedor.setLayout(painelRmvVendedorLayout);
        painelRmvVendedorLayout.setHorizontalGroup(
            painelRmvVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRmvVendedorLayout.createSequentialGroup()
                .addContainerGap(220, Short.MAX_VALUE)
                .addGroup(painelRmvVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rmvVendPrevTurnoLabel)
                    .addComponent(rmvVendPrevLoginLabel)
                    .addComponent(rmvVendPrevEmailLabel)
                    .addComponent(rmvVendedorCPF)
                    .addGroup(painelRmvVendedorLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(rmvVendBtnClear))
                    .addComponent(rmvVendPrevEmail)
                    .addComponent(rmvVendedorCPFLabel)
                    .addComponent(rmvVendPrevLogin)
                    .addComponent(rmvVendPrevTurno))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        painelRmvVendedorLayout.setVerticalGroup(
            painelRmvVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRmvVendedorLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(rmvVendedorCPFLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rmvVendedorCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rmvVendPrevEmailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rmvVendPrevEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rmvVendPrevLoginLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rmvVendPrevLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rmvVendPrevTurnoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rmvVendPrevTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(rmvVendBtnClear)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        removerTabs.addTab("Vendedor", painelRmvVendedor);

        javax.swing.GroupLayout gerentePanelRemLayout = new javax.swing.GroupLayout(gerentePanelRem);
        gerentePanelRem.setLayout(gerentePanelRemLayout);
        gerentePanelRemLayout.setHorizontalGroup(
            gerentePanelRemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(removerTabs, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        gerentePanelRemLayout.setVerticalGroup(
            gerentePanelRemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(removerTabs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );

        tabsGerente.addTab("Remover", gerentePanelRem);

        tituloPainelGerente.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        tituloPainelGerente.setText("Painel do Gerente");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloPainelGerente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabsGerente)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloPainelGerente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabsGerente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void newFilmeNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFilmeNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newFilmeNomeActionPerformed

    private void newSalaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSalaNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newSalaNomeActionPerformed

    private void newFilmeBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFilmeBtnSaveActionPerformed
        //Validação dos campos informados

        if (newFilmeNome.getText().isEmpty()) {
            newFilmeNome.requestFocus();
            Msgs.displayErrorJOP("Erro! O nome do filme não pode ser vazio.", this);
            return;
        }
        if (newFilmeSinopse.getText().isEmpty()) {
            newFilmeSinopse.requestFocus();
            Msgs.displayErrorJOP("Erro! A sinopse não pode ser vazia.", this);
            return;
        }
        if (newFilmeGeneros.getText().isEmpty()) {
            newFilmeGeneros.requestFocus();
            Msgs.displayErrorJOP("Erro! O filme requer ao menos um gênero.", this);
            return;
        }
        Filme f = new Filme(newFilmeNome.getText(), newFilmeSinopse.getText(), newFilmeGeneros.getText(), newFilmeAno.getValue());
        listaFilmes.add(f);
        f.sendToBD();
        System.out.println(f.getFilmeNome());
        System.out.println(f.getFilmeSinopse());
        System.out.println(f.getFilmeAno());
        System.out.println(f.getFilmeGeneros());
        Msgs.displaySucessJOP("O filme foi registrado com sucesso!", this);
        newFilmeAno.setValue(2000);
        newFilmeGeneros.setText("");
        newFilmeNome.setText("");
        newFilmeSinopse.setText("");
    }//GEN-LAST:event_newFilmeBtnSaveActionPerformed

    private void newFilmeAnoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_newFilmeAnoStateChanged
        newFilmeAnoCurrent.setText("" + newFilmeAno.getValue());
    }//GEN-LAST:event_newFilmeAnoStateChanged

    private void newSalaBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSalaBtnClearActionPerformed
        newSalaNome.setText("");
        newSalaCod.setText("");
    }//GEN-LAST:event_newSalaBtnClearActionPerformed

    private void newFilmeBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFilmeBtnClearActionPerformed
        newFilmeAno.setValue(2000);
        newFilmeGeneros.setText("");
        newFilmeNome.setText("");
        newFilmeSinopse.setText("");
    }//GEN-LAST:event_newFilmeBtnClearActionPerformed

    private void newSessaoBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSessaoBtnClearActionPerformed
        newSessaoHoras.setText("");
        newSessaoMinutos.setText("");
        newSessaoFilme.setSelectedIndex(0);
        newSessaoSala.setSelectedIndex(0);
        newSessaoPreco.setText("");
    }//GEN-LAST:event_newSessaoBtnClearActionPerformed

    private void newVendedorBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newVendedorBtnClearActionPerformed
        newVendedorEmail.setText("");
        newVendedorLogin.setText("");
        newVendedorSenha.setText("");
        newVendedorCPF.setText("");
        newVendedorTurno.setSelectedIndex(0);
    }//GEN-LAST:event_newVendedorBtnClearActionPerformed

    private void rmvSessaoBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmvSessaoBtnClearActionPerformed
        rmvSessaoOpt.setSelectedIndex(0);
    }//GEN-LAST:event_rmvSessaoBtnClearActionPerformed

    private void newVendedorBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newVendedorBtnSaveActionPerformed
        if (newVendedorCPF.getText().isEmpty()) {
            System.out.println("No CPF");
            newVendedorCPF.requestFocus();
            Msgs.displayErrorJOP("O CPF informado é inválido (vazio).", this);
            return;
        } else if (newVendedorCPF.getText().length() < 11) {
            System.out.println("Invalid CPF");
            newVendedorCPF.requestFocus();
            Msgs.displayErrorJOP("O CPF informado é inválido (menor que 11 caracteres).", this);
            return;
        }
        if (newVendedorEmail.getText().isEmpty()) {
            System.out.println("No email");
            newVendedorEmail.requestFocus();
            Msgs.displayErrorJOP("O email informado é inválido (vazio).", this);
            return;
        }
        if (newVendedorLogin.getText().isEmpty()) {
            System.out.println("No login");
            newVendedorLogin.requestFocus();
            Msgs.displayErrorJOP("O login informado é inválido (vazio)", this);
            return;
        }
        if (Arrays.toString(newVendedorSenha.getPassword()).isEmpty()) {
            System.out.println("No password");
            Msgs.displayErrorJOP("A senha informada é inválida (vazia).", this);
            newVendedorSenha.requestFocus();
            return;
        }
        Vendedor vendedor = new Vendedor(newVendedorLogin.getText(), newVendedorSenha.getPassword(), (String) newVendedorTurno.getSelectedItem(), newVendedorEmail.getText(), newVendedorCPF.getText());
        System.out.println(newVendedorCPF.getText());
        System.out.println(newVendedorEmail.getText());
        System.out.println(newVendedorLogin.getText());
        System.out.println(newVendedorTurno.getSelectedItem());
        System.out.println(newVendedorSenha.getPassword());
        vendedor.sendToDB();
        loadDAOs();
    }//GEN-LAST:event_newVendedorBtnSaveActionPerformed

    private void loadDAOs() {
        try {
            listaVendedores = VendedorDAO.getVendedores();
            listaFilmes = FilmeDAO.getFilmes();
            listaSalas = SalaDAO.getSalas();

        } catch (SQLException ex) {
            Logger.getLogger(PainelGerente.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadVendedorHashMap();
        loadFilmeHashMap();
    }

    private void rmvVendedorCPFPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_rmvVendedorCPFPropertyChange
    }//GEN-LAST:event_rmvVendedorCPFPropertyChange

    private void rmvVendedorCPFCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_rmvVendedorCPFCaretPositionChanged
        /*HashMap<String, Integer> cpfs = new HashMap<>();
        System.out.println("Ata");
        if (!listaVendedores.isEmpty()) {
            for (int i = 0; i < listaVendedores.size(); i++) {
                cpfs.put(listaVendedores.get(i).getCpf(), i);
            }

            if (cpfs.containsKey(rmvVendedorCPF.getText())) {
                rmvVendPrevEmail.setText(listaVendedores.get(cpfs.get(rmvVendedorCPF.getText())).getEmail());
                rmvVendPrevTurno.setText(listaVendedores.get(cpfs.get(rmvVendedorCPF.getText())).getTurno());
                rmvVendPrevLogin.setText(listaVendedores.get(cpfs.get(rmvVendedorCPF.getText())).getLogin_pessoa().getUserName());
            } else {
                rmvVendPrevEmail.setText("");
                rmvVendPrevTurno.setText("");
                rmvVendPrevLogin.setText("");
            }
        }*/


    }//GEN-LAST:event_rmvVendedorCPFCaretPositionChanged

    private void newSalaBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSalaBtnSaveActionPerformed
        if (newSalaCod.getText().isEmpty()) {
            newSalaCod.requestFocus();
            Msgs.displayErrorJOP("Erro! Código da sala invgálido.", this);
            return;
        }
        if (newSalaNome.getText().isEmpty()) {
            newSalaNome.requestFocus();
            Msgs.displayErrorJOP("Erro! Nome da sala inválido.", this);
            return;
        }
        Sala s = new Sala(newSalaNome.getText(), newSalaCod.getText());
        System.out.println(s.getCod());
        System.out.println(s.getNome());
        s.sendToBD();
    }//GEN-LAST:event_newSalaBtnSaveActionPerformed

    private void newSessaoHorasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newSessaoHorasFocusLost
        System.out.println(/*Integer.parseInt(*/newSessaoHoras.getText()/*)*/);
        if (newSessaoHoras.getText().isEmpty()) {
            System.out.println("Idade empty");
        } else if (Integer.parseInt(newSessaoHoras.getText()) > 150) {
            newSessaoHoras.setText("150");
        } else if (Integer.parseInt(newSessaoHoras.getText()) < 18) {
            newSessaoHoras.setText("18");
        }
    }//GEN-LAST:event_newSessaoHorasFocusLost

    private void newSessaoHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSessaoHorasActionPerformed

    }//GEN-LAST:event_newSessaoHorasActionPerformed

    private void newSessaoHorasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_newSessaoHorasPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_newSessaoHorasPropertyChange

    private void newSessaoHorasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newSessaoHorasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_newSessaoHorasKeyTyped

    private void newSessaoMinutosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newSessaoMinutosFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_newSessaoMinutosFocusLost

    private void newSessaoMinutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSessaoMinutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newSessaoMinutosActionPerformed

    private void newSessaoMinutosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_newSessaoMinutosPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_newSessaoMinutosPropertyChange

    private void newSessaoMinutosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newSessaoMinutosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_newSessaoMinutosKeyTyped

    private void newSessaoSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSessaoSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newSessaoSalaActionPerformed

    private void newSessaoBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSessaoBtnSaveActionPerformed
        if (newSessaoPreco.getText().isEmpty()) {
            newSessaoPreco.requestFocus();
            Msgs.displayErrorJOP("Erro! O preço não é válido.", this);
            return;
        }
        if (newSessaoHoras.getText().isEmpty()) {
            newSessaoHoras.requestFocus();
            Msgs.displayErrorJOP("Erro! A hora não é válida.", this);
            return;
        }
        if (newSessaoMinutos.getText().isEmpty()) {
            newSessaoMinutos.requestFocus();
            Msgs.displayErrorJOP("Erro! Os minutos não são válidos.", this);
            return;
        }
        //Por algum motivo está dando erro.
        Sessao s = new Sessao(Float.parseFloat(newSessaoPreco.getText()), Integer.parseInt(newSessaoHoras.getText()), Integer.parseInt(newSessaoMinutos.getText()));
        s.sendToBD();
    }//GEN-LAST:event_newSessaoBtnSaveActionPerformed

    private void newSessaoPrecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newSessaoPrecoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_newSessaoPrecoFocusLost

    private void newSessaoPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSessaoPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newSessaoPrecoActionPerformed

    private void newSessaoPrecoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_newSessaoPrecoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_newSessaoPrecoPropertyChange

    private void newSessaoPrecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newSessaoPrecoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_newSessaoPrecoKeyTyped

    private void rmvFilmeBtnYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmvFilmeBtnYesActionPerformed
        Filme f = ftm.get(rmvFilmeTable.getSelectedRow());
        try {
            FilmeDAO.deletaFilme(f.getFilmeNome(), f.getFilmeAno());
            ftm.removeRow(rmvFilmeTable.getSelectedRow());
            Msgs.displaySucessJOP("O filme \"" + f.getFilmeNome() + "\" foi excluído com sucesso!", this);
        } catch (SQLException ex) {
            Logger.getLogger(PainelGerente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rmvFilmeBtnYesActionPerformed

    private void rmvSalaBtnYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmvSalaBtnYesActionPerformed
        if (!listaSalas.isEmpty()) {
            for (Sala sala : listaSalas) {
                if (rmvSalaOpt.getText().equals(sala.getCod())) {
                    try {
                        SalaDAO.removeSala(sala);
                        listaSalas = SalaDAO.getSalas();
                        break;
                    } catch (SQLException ex) {
                        Logger.getLogger(PainelGerente.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        } else {
            Msgs.displayErrorJOP("Erro! Não há salas registradas.", this);
        }
    }//GEN-LAST:event_rmvSalaBtnYesActionPerformed

    private void rmvVendedorCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rmvVendedorCPFKeyPressed
        if (vends.containsKey(rmvVendedorCPF.getText())) {
            String cpf = rmvVendedorCPF.getText();
            rmvVendPrevLogin.setText(listaVendedores.get(vends.get(cpf)).getLogin_pessoa().getUserName());
            rmvVendPrevEmail.setText(listaVendedores.get(vends.get(cpf)).getEmail());
            rmvVendPrevTurno.setText(listaVendedores.get(vends.get(cpf)).getTurno());
        } else {
            rmvVendPrevLogin.setText("");
            rmvVendPrevEmail.setText("");
            rmvVendPrevTurno.setText("");
        }
    }//GEN-LAST:event_rmvVendedorCPFKeyPressed

    private void rmvVendedorCPFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rmvVendedorCPFKeyReleased
        rmvVendedorCPFKeyPressed(evt);
    }//GEN-LAST:event_rmvVendedorCPFKeyReleased

    private void loadVendedorHashMap() {
        vends = new HashMap<>();
        int i = 0;
        for (Vendedor vend : listaVendedores) {
            vends.put(vend.getCpf(), i);
            i++;
        }
    }

    private void loadFilmeHashMap() {
        films = new HashMap<>();
        int i = 0;
        for (Filme vend : listaFilmes) {
            vends.put(vend.getFilmeNome() + " -- " + vend.getFilmeAno(), i);
            i++;
        }
    }

//    private JComboBox<> getComboBoxFromClass(Class c) {
    //  }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new PainelGerente().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane adicionarTabs;
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel gerentePanelAdd;
    private javax.swing.JPanel gerentePanelRem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider newFilmeAno;
    private javax.swing.JLabel newFilmeAnoCurrent;
    private javax.swing.JLabel newFilmeAnoCurrentLabel;
    private javax.swing.JLabel newFilmeAnoLabel;
    private javax.swing.JButton newFilmeBtnClear;
    private javax.swing.JButton newFilmeBtnSave;
    private javax.swing.JLabel newFilmeGenLabel;
    private javax.swing.JTextField newFilmeGeneros;
    private javax.swing.JTextField newFilmeNome;
    private javax.swing.JLabel newFilmeNomeLabel;
    private javax.swing.JTextArea newFilmeSinopse;
    private javax.swing.JLabel newFilmeSinposeLabel;
    private javax.swing.JButton newSalaBtnClear;
    private javax.swing.JButton newSalaBtnSave;
    private javax.swing.JTextField newSalaCod;
    private javax.swing.JLabel newSalaCodLabel;
    private javax.swing.JTextField newSalaNome;
    private javax.swing.JLabel newSalaNomeLabel;
    private javax.swing.JButton newSessaoBtnClear;
    private javax.swing.JButton newSessaoBtnSave;
    private javax.swing.JComboBox<Object> newSessaoFilme;
    private javax.swing.JLabel newSessaoFilmeLabel;
    private javax.swing.JTextField newSessaoHoras;
    private javax.swing.JTextField newSessaoMinutos;
    private javax.swing.JTextField newSessaoPreco;
    private javax.swing.JLabel newSessaoPrecoLabel;
    private javax.swing.JComboBox<Object> newSessaoSala;
    private javax.swing.JLabel newSessaoSalaLabel;
    private javax.swing.JLabel newSessaoTime;
    private javax.swing.JLabel newSessaoTime1;
    private javax.swing.JButton newVendedorBtnClear;
    private javax.swing.JButton newVendedorBtnSave;
    private javax.swing.JTextField newVendedorCPF;
    private javax.swing.JLabel newVendedorCPFLabel;
    private javax.swing.JTextField newVendedorEmail;
    private javax.swing.JLabel newVendedorEmailLabel;
    private javax.swing.JTextField newVendedorLogin;
    private javax.swing.JLabel newVendedorLoginLabel;
    private javax.swing.JPasswordField newVendedorSenha;
    private javax.swing.JLabel newVendedorSenhaLabel;
    private javax.swing.JComboBox<String> newVendedorTurno;
    private javax.swing.JLabel newVendedorTurnoLabel;
    private javax.swing.JPanel painelAddSala;
    private javax.swing.JPanel painelAddSessao;
    private javax.swing.JPanel painelAddVendedor;
    private javax.swing.JPanel painelRmvFilme;
    private javax.swing.JPanel painelRmvSala;
    private javax.swing.JPanel painelRmvSessao;
    private javax.swing.JPanel painelRmvVendedor;
    private javax.swing.JPanel panelAddFilme;
    private javax.swing.JTabbedPane removerTabs;
    private javax.swing.JButton rmvFilmeBtnYes;
    private javax.swing.JLabel rmvFilmeOptLabel;
    private javax.swing.JTable rmvFilmeTable;
    private javax.swing.JScrollPane rmvFilmeTableOutside;
    private javax.swing.JButton rmvSalaBtnYes;
    private javax.swing.JTextField rmvSalaOpt;
    private javax.swing.JLabel rmvSalaOptLabel;
    private javax.swing.JButton rmvSessaoBtnClear;
    private javax.swing.JButton rmvSessaoBtnYes;
    private javax.swing.JComboBox<String> rmvSessaoOpt;
    private javax.swing.JLabel rmvSessaoOptLabel;
    private javax.swing.JButton rmvVendBtnClear;
    private javax.swing.JTextField rmvVendPrevEmail;
    private javax.swing.JLabel rmvVendPrevEmailLabel;
    private javax.swing.JTextField rmvVendPrevLogin;
    private javax.swing.JLabel rmvVendPrevLoginLabel;
    private javax.swing.JTextField rmvVendPrevTurno;
    private javax.swing.JLabel rmvVendPrevTurnoLabel;
    private javax.swing.JTextField rmvVendedorCPF;
    private javax.swing.JLabel rmvVendedorCPFLabel;
    private javax.swing.JTabbedPane tabsGerente;
    private javax.swing.JLabel tituloPainelGerente;
    // End of variables declaration//GEN-END:variables

}
